name: paseo
version: '0.1.0.0'
category: Web
author: Kit Dallege
maintainer: kitdallege@gmail.com
copyright: ! 'Copyright: (c) 2017 Kit Dallege'
license: BSD3
homepage: https://github.com/kitdallege/paseo#readme
extra-source-files:
- README.md

ghc-options:
- -Wall
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -O2
- -Wall
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -O2

dependencies:
- base >=4.7 && <5
- aeson
- blaze-html
- bytestring
- charlotte
- containers
- directory
- filepath
- http-types
- mtl
- network-uri
- scotty
- sqlite-simple
- tagsoup
- tagsoup-selection
- text
- time
- wai
- wai-extra



library:
  source-dirs: src

executables:
  paseo:
    main: Main.hs
    source-dirs: app
    dependencies:
      - paseo


  paseo-spider:
    main: Spider.hs
    source-dirs: app
    dependencies:
      - paseo
