name: paseo
version: '0.1.0.0'
category: Web
author: Kit Dallege
maintainer: kitdallege@gmail.com
copyright: ! 'Copyright: (c) 2017 Kit Dallege'
license: BSD3
homepage: https://github.com/kitdallege/paseo#readme
extra-source-files:
- README.md

ghc-options:
- -Wall
- -O2

dependencies:
- base >=4.7 && <5
- aeson
- aeson-pretty
- async
- blaze-html
- bytestring
- charlotte
- containers
- digestive-functors
- digestive-functors-blaze
- directory
- filepath
- http-types
- mtl
- network-uri
- process
- scotty
- stm
- sqlite-simple
- tagsoup
- tagsoup-selection
- text
- time
- vector
- wai
- wai-extra

library:
  source-dirs: src

executables:
  paseo: &paseo-exe
    main: Main.hs
    source-dirs: app
    dependencies:
      - paseo
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
  paseo-spider:
    <<: *paseo-exe
    main: Spider.hs
